First working base-structure
Abilium-Odoo/abilium_meeting_scheduler pull request #1
Opened 2023-03-10 16:40 UTC by NilsNeeb

Created first working base-structure

2023-03-11 07:02 UTC, szumbrunn commented on models/models.py
> +class meeting__scheduler(models.Model):
@NilsNeeb Don't use two successive underscores in object names. The odoo code convention is snake case

2023-03-11 07:02 UTC, szumbrunn commented on models/models.py
> +    _name = 'meeting__scheduler.meeting__scheduler'
@NilsNeeb You can call the object e.g. "meeting.scheduler" that's totally fine, then you don't have that repetition

2023-03-11 07:04 UTC, szumbrunn commented on models/models.py
> +    name = fields.Char()
@NilsNeeb Always set a label to fields: fields.Char(string="set label like this") then those can be translated later on. You can actually use german for the labels

2023-03-15 12:54 UTC, SandroCalce requested changes
Please add newlines to all the files mentioned

2023-03-15 12:54 UTC, SandroCalce commented on demo/demo.xml
> +</odoo>
No newline at end of file

2023-03-15 12:54 UTC, SandroCalce commented on controllers/__init__.py
> +from . import controllers
No newline at end of file

2023-03-15 12:54 UTC, SandroCalce commented on models/__init__.py
No newline at end of File

2023-03-15 12:54 UTC, SandroCalce commented on __init__.py
> +from . import models
No newline at end of file

2023-03-15 12:54 UTC, SandroCalce commented on security/ir.model.access.csv
No newline at end of file

2023-03-15 12:54 UTC, SandroCalce commented on views/views.xml
No newline at end of file

2023-03-15 12:56 UTC, Lvk-v requested changes
see models/models.py comments

2023-03-15 12:56 UTC, Lvk-v commented on models/models.py
> +    frequency = fields.Selection([('0', 'Not repeating'), ('1', 'Weekly'), ('2', 'Biweekly')], store=True,
describe variable names more expressive, for example meetingName, meetingStartDate, meetingLocation ...

2023-03-15 13:07 UTC, Lvk-v approved these changes

2023-03-15 13:08 UTC, SandroCalce approved these changes

2023-03-15 13:09 UTC, merged